DROP SEQUENCE SEQ_COCHES;

DROP TABLE PILOTOS CASCADE CONSTRAINTS;
DROP TABLE COCHES CASCADE CONSTRAINTS;
DROP TABLE ESCUDERIAS CASCADE CONSTRAINTS;


CREATE TABLE PILOTOS
(
  REF         VARCHAR2(10),
  MARCA	      VARCHAR2(256),
  NOMBRE      VARCHAR2(256),
  APELLIDOS   VARCHAR2(256),
  TITULOS     NUMBER(5),
  CONSTRAINT "PK_PILOTOS" PRIMARY KEY (REF),
  CONSTRAINT "NN_PILOTOS.MARCA" CHECK (MARCA IS NOT NULL),
  CONSTRAINT "NN_PILOTOS.NOMBRE" CHECK (NOMBRE IS NOT NULL),
  CONSTRAINT "NN_PILOTOS.APELLIDOS" CHECK (APELLIDOS IS NOT NULL),
  CONSTRAINT "NN_PILOTOS.TITULOS" CHECK (TITULOS IS NOT NULL)
);

CREATE TABLE COCHES
(
  ID         VARCHAR2(10),
  MARCA      VARCHAR2(256),
  MODELO     VARCHAR2(256),	
  CV         NUMBER(5),
  VMAX       NUMBER(10,2),
  CONSTRAINT "PK_COCHES" PRIMARY KEY (ID),
  CONSTRAINT "NN_COCHES.MARCA" CHECK (MARCA IS NOT NULL),
  CONSTRAINT "NN_COCHES.MODELO" CHECK (MODELO IS NOT NULL),
  CONSTRAINT "NN_COCHES.CV" CHECK (CV IS NOT NULL),
  CONSTRAINT "NN_COCHES.VMAX" CHECK (VMAX IS NOT NULL)
);

CREATE TABLE ESCUDERIAS
(
  MARCA       VARCHAR2(256),
  REF         VARCHAR2(10),
  ID          VARCHAR2(10),
  CONSTRAINT "UK_ESCUDERIAS.REF" UNIQUE(REF),
  CONSTRAINT "NN_ESCUDERIAS.MARCA" CHECK (MARCA IS NOT NULL),
  CONSTRAINT "NN_ESCUDERIAS.REF" CHECK (REF IS NOT NULL),
  CONSTRAINT "NN_ESCUDERIAS.ID" CHECK (ID IS NOT NULL),
  CONSTRAINT "FK_ESCUDERIAS.REF"     FOREIGN KEY (REF)     REFERENCES PILOTOS(REF),
  CONSTRAINT "FK_ESCUDERIAS.ID"      FOREIGN KEY (ID)      REFERENCES COCHES(ID)
);


CREATE SEQUENCE SEQ_COCHES
          MINVALUE 5
          MAXVALUE 9999998
          START WITH 5
          INCREMENT BY 1;

INSERT INTO COCHES(ID, MARCA, MODELO, CV, VMAX)
                VALUES(1, 'Alpine', 'A521', '990', '360');
INSERT INTO COCHES(ID, MARCA, MODELO, CV, VMAX)
                VALUES(2, 'Ferrari', 'SF21', '990', '360');
INSERT INTO COCHES(ID, MARCA, MODELO, CV, VMAX)
                VALUES(3, 'Mercedes', 'W12', '990', '360');
INSERT INTO COCHES(ID, MARCA, MODELO, CV, VMAX)
                VALUES(4, 'Mclaren', 'MCL35M', '990', '360');

INSERT INTO PILOTOS(REF, MARCA, NOMBRE, APELLIDOS, TITULOS)
                VALUES('0000A', 'Alpine', 'Fernando', 'Alonso', '2');
INSERT INTO PILOTOS(REF, MARCA, NOMBRE, APELLIDOS, TITULOS)
                VALUES('0000B', 'Ferrari', 'Carlos', 'Sainz', '0');
INSERT INTO PILOTOS(REF, MARCA, NOMBRE, APELLIDOS, TITULOS)
                VALUES('0000C', 'Mercedes', 'Lewins', 'Hamilton', '7');
INSERT INTO PILOTOS(REF, MARCA, NOMBRE, APELLIDOS, TITULOS)
                VALUES('0000D', 'Mclaren', 'Lando', 'Norris', '0');

INSERT INTO ESCUDERIAS(MARCA, REF, ID)
                VALUES('Alpine', '0000A', '1');
INSERT INTO ESCUDERIAS(MARCA, REF, ID)
                VALUES('Ferrari', '0000B', '2');
INSERT INTO ESCUDERIAS(MARCA, REF, ID)
                VALUES('Mercedes', '0000C', '3');
INSERT INTO ESCUDERIAS(MARCA, REF, ID)
                VALUES('Mclaren', '0000D', '4');



commit;